yatube/about/urls.py
# файл about/urls.py
from django.urls import path
from . import views


app_name = 'about'

urlpatterns = [
    path('author/', views.AboutAuthorView.as_view(), name='author'),
    path('tech/', views.AboutTechView.as_view(), name='tech'),
]

yatube/posts/urls.py
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static

from . import views


app_name = 'posts'


urlpatterns = [
    path('', views.index, name='index'),
    path('group/<slug:slug>/', views.group_posts, name='group_posts'),
    path('profile/<str:username>/', views.profile, name='profile'),
    path('posts/<int:post_id>/comment/', views.add_comment, name='add_comment'),
    path('posts/<int:post_id>/', views.post_detail, name='post_detail'),
    path('create/', views.post_create, name='post_create'),
    path('posts/<int:post_id>/edit/', views.post_edit, name='post_edit'),
    path('follow/', views.follow_index, name='follow_index'),
    path(
        'profile/<str:username>/follow/',
        views.profile_follow,
        name='profile_follow'
    ),
    path(
        'profile/<str:username>/unfollow/',
        views.profile_unfollow,
        name='profile_unfollow'
    ),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

yatube/yatube/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('about/', include('about.urls', namespace='about')),
    path('admin/', admin.site.urls),
    path('auth/', include('users.urls')),
    path('auth/', include('django.contrib.auth.urls')),
    path('', include('posts.urls', namespace='posts')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL, document_root=settings.MEDIA_ROOT
    )

handler404 = 'core.views.page_not_found'
handler403 = 'core.views.permission_denied'
handler500 = 'core.views.server_error'

yatube/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class Group(models.Model):
    title = models.CharField(max_length=200)
    slug = models.SlugField(unique=True)
    description = models.TextField()

    def __str__(self):
        return self.title


class Post(models.Model):
    text = models.TextField(
        'Текст поста',
        help_text='Введите текст поста'
    )
    pub_date = models.DateTimeField(
        'Дата публикации',
        auto_now_add=True
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='posts',
        verbose_name='Автор'
    )
    group = models.ForeignKey(
        Group,
        on_delete=models.SET_NULL,
        related_name='posts',
        blank=True,
        null=True,
        verbose_name='Группа',
        help_text='Группа, к которой будет относиться пост'
    )
    image = models.ImageField(
        'Картинка',
        upload_to='posts/',
        blank=True
    )

    class Meta:
        ordering = ("-pub_date",)
        verbose_name = 'Пост'
        verbose_name_plural = 'Посты'

    def __str__(self):
        return self.text[:15]


class Comment(models.Model):
    post = models.ForeignKey(
        Post,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Комментарий'
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='comments',
        verbose_name='Автор комментария'
    )
    text = models.TextField(
        verbose_name='Текст комментария',
        help_text='Введите текст комментария'
    )
    created = models.DateTimeField(
        verbose_name='Дата комментария',
        auto_now_add=True
    )

    class Meta:
        ordering = ("-created",)
        verbose_name = 'Комментарий'
        verbose_name_plural = 'Комментарии'

    def __str__(self):
        return self.text[:15]


class Follow(models.Model):
    user = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='follower',
    )
    author = models.ForeignKey(
        User,
        on_delete=models.CASCADE,
        related_name='following',
    )

    class Meta:
        verbose_name = 'Подписка'
        verbose_name_plural = 'Подписки'

yatube/posts/forms.py
from django import forms

from .models import Post, Comment, Follow


class PostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('text', 'group', 'image')


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('text',)


class FollowForm(forms.ModelForm):
    class Meta:
        model = Follow
        fields = ('user', 'author')

yatube/posts/views.py
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, redirect, render
from django.views.decorators.csrf import csrf_protect
# from django.views.decorators.cache import cache_page


from .forms import PostForm, CommentForm
from .models import Group, Post, User, Comment, Follow
from .utils import external_paginator


# @cache_page(20, key_prefix='index_page')
def index(request):
    post_list = Post.objects.select_related('group', 'author')

    context = {
        'page_obj': external_paginator(request, post_list),
    }
    return render(request, 'posts/index.html', context)


def profile(request, username):
    author = get_object_or_404(User, username=username)
    post_list = author.posts.all()
    posts_comment = author.comments.all()
    user = request.user
    following = Follow.objects.filter(author=author, user=request.user.id)

    context = {
        'author': author,
        'page_obj': external_paginator(request, post_list),
        'comments': posts_comment,
        "following": following,
        'user': user,
    }
    return render(request, 'posts/profile.html', context)


def post_detail(request, post_id):
    post_info = get_object_or_404(Post, pk=post_id)
    form = CommentForm()
    posts_comment = Comment.objects.select_related('post').filter(post=post_id)

    context = {
        'post_info': post_info,
        'post_id': post_id,
        'form': form,
        'comments': posts_comment,
    }
    return render(request, 'posts/post_detail.html', context)


def group_posts(request, slug):
    group = get_object_or_404(Group, slug=slug)
    post_list = group.posts.all()

    context = {
        'group': group,
        'page_obj': external_paginator(request, post_list),
    }
    return render(request, 'posts/group_list.html', context)


@login_required
@csrf_protect
def post_create(request):
    user = request.user
    if request.method == 'POST':
        form = PostForm(
            request.POST or None,
            files=request.FILES or None)

        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            return redirect('posts:profile', user.username)
    else:
        form = PostForm()
    return render(request, 'posts/create_post.html', {'form': form})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    if post.author != request.user:
        return redirect('posts:post_detail', post_id=post_id)

    form = PostForm(
        request.POST or None,
        files=request.FILES or None,
        instance=post
    )
    if form.is_valid():
        form.save()
        return redirect('posts:post_detail', post_id=post_id)
    context = {
        'post': post,
        'form': form,
        'is_edit': True,
    }
    return render(request, 'posts/create_post.html', context)


@login_required
def add_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    form = CommentForm(request.POST or None)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.author = request.user
        comment.post = post
        comment.save()
    return redirect('posts:post_detail', post_id=post_id)


@login_required
def follow_index(request):
    posts = Post.objects.filter(author__following__user=request.user)
    context = {
        'page_obj': external_paginator(request, posts),
    }
    return render(request, 'posts/follow.html', context)


@login_required
def profile_follow(request, username):
    author = get_object_or_404(User, username=username)
    if author != request.user and not Follow.objects.filter(
        user=request.user, author=author
    ).exists():
        Follow.objects.create(user=request.user, author=author)
    return redirect("posts:profile", username=username)


@login_required
def profile_unfollow(request, username):
    author = get_object_or_404(User, username=username)
    if Follow.objects.filter(user=request.user, author=author).exists():
        Follow.objects.get(user=request.user, author=author).delete()
    return redirect("posts:profile", username=username)

yatube/templates/posts/create_post.html
{#{% extends 'base.html' %}#}
{#{% block title %}#}
{#  {{ title }}#}
{#{% endblock %}#}
{#{% load thumbnail %}#}
{#{% block content %}#}
{#  <div class="container py-5">#}
{#    <div class="row justify-content-center">#}
{#      <div class="col-md-8 p-5">#}
{#        <div class="card">#}
{#          <div class="card-header">#}
{#            {% if is_edit %}#}
{#              Редактировать запись#}
{#            {% else %}#}
{#              Добавить запись#}
{#            {% endif %}#}
{#          </div>#}
{#            <div class="card-body">#}
{#            {% load user_filters %}#}
{#                {% if form.errors %}#}
{#                  {% for field in form %}#}
{#                    {% for error in field.errors %}#}
{#                      <div class="alert alert-danger">#}
{#                        {{ error|escape }}#}
{#                      </div>#}
{#                    {% endfor %}#}
{#                  {% endfor %}#}
{#                  {% for error in form.non_field_errors %}#}
{#                    <div class="alert alert-danger">#}
{#                      {{ error|escape }}#}
{#                    </div>#}
{#                  {% endfor %}#}
{#                {% endif %}#}
{#                <form method="post" enctype="multipart/form-data"#}
{#                  {% if is_edit %}#}
{#                    action="{% url 'posts:post_edit' post.id %}"#}
{#                  {% else %}#}
{#                    action="{% url 'posts:post_create' %}"#}
{#                  {% endif %}>#}
{#                  {% csrf_token %}#}
{#                 Выводим поля в цикле, по отдельности#}
{#                {% for field in form %}#}
{#                  <div class="form-group row my-3">#}
{#                    <label for="{{ field.id_for_label }}">#}
{#                      {{ field.label }}#}
{#                        {% if field.field.required %}#}
{#                          <span class="required text-danger">*</span>#}
{#                      {% endif %}#}
{#                    </label>#}
{#                     К полю ввода добавляем атрибут class#}
{#                    {{ field|addclass:'form-control'}}#}
{#                      {% if field.help_text %}#}
{#                        <small#}
{#                          id="{{ field.id_for_label }}-help"#}
{#                          class="form-text text-muted"#}
{#                      >#}
{#                          {{ field.help_text|safe }}#}
{#                        </small>#}
{#                      {% endif %}#}
{#                  </div>#}
{#                {% endfor %}#}
{#                <div class="col-md-6 offset-md-4">#}
{#                  <button type="submit" class="btn btn-primary">#}
{#                    {% if is_edit %}#}
{#                      Добавить#}
{#                    {% else %}#}
{#                      Сохранить#}
{#                    {% endif %}#}
{#                  </button>#}
{#                </div>#}
{#              </form>#}
{#            </div> <!-- card body -->#}
{#          </div> <!-- card -->#}
{#        </div> <!-- col -->#}
{#      </div> <!-- row -->#}
{#{% endblock %}#}

{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Новый пост{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
        <div class="row justify-content-center">
          <div class="col-md-8 p-5">
            <div class="card">
              <div class="card-header">
                Новый пост
              </div>
              <div class="card-body">
                <form method="post" enctype="multipart/form-data">
                {% csrf_token %}

                  <div class="form-group row my-3 p-3">
                    <label for="id_text">
                      Текст поста
                      <span class="required text-danger" >*</span>
                    </label>

                  {% if is_edit %}
                    {{ form.text }}
                    {{ form.image }}
                  {% else %}
                    {{ form.text }}
                    {{ form.image }}
                  {%  endif %}

                    <small id="id_text-help" class="form-text text-muted">
                      Текст нового поста
                    </small>
                  </div>
                  <div class="form-group row my-3 p-3">
                    <label for="id_group">
                      Группа
                    </label>
                  {% if is_edit %}
{#                    <select name="group" class="form-control" id="id_group">#}
                      {{ form.group }}
{#                    </select>#}
                  {% else %}
                    {{ form.group }}
                  {% endif %}
                    <small id="id_group-help" class="form-text text-muted">
                      Группа, к которой будет относиться пост
                    </small>
                  </div>

                  <div class="d-flex justify-content-end">
                    <button type="submit" class="btn btn-primary">
                      {% if is_edit %}
                        Сохранить
                      {% else %}
                        Добавить
                      {% endif %}
                    </button>
                  </div>
                {% if post.group %}
                    <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
                {% endif %}
                </form>
              </div>
            </div>
          </div>
        </div>
      </div>
    </main>
{% endblock %}



{#{% extends "base.html" %}#}
{#{% block title %}Новый пост{% endblock %}#}
{#{% block content %}#}
{##}
{#{% load thumbnail %}#}
{##}
{#    <main>#}
{#      <div class="container py-5">#}
{#        <div class="row justify-content-center">#}
{#          <div class="col-md-8 p-5">#}
{#            <div class="card">#}
{##}
{#              <div class="card-header">#}
{#                Новый пост#}
{#              </div>#}
{##}
{#              <div class="card-body">#}
{#                <form method="post" enctype="multipart/form-data">#}
{#                <form method="post" action="{% url 'posts:post_create' %}">#}
{#                {% csrf_token %}#}
{##}
{#                {% for field in form %}#}
{##}
{#                  <input type="hidden" name="{% csrf_token %}" value="Новый пост">#}
{##}
{#                      <div class="form-group row my-3 p-3">#}
{#                            <label for="id_text">#}
{#                              Текст поста#}
{#                              <span class="required text-danger" >*</span>#}
{#                            </label>#}
{##}
{#                          {% if is_edit %}#}
{#                            {{ form.text }}#}
{#                              <p>#}
{#                              <p>#}
{#                            {{ form.image }}#}
{#                          {% else %}#}
{#                            {{ form.text }}#}
{#                              <small id="id_text-help" class="form-text text-muted">#}
{#                              Текст нового поста#}
{#                              </small>#}
{#                              <p>#}
{#                              <p>#}
{#                            {{ form.image }} Загрузить картинку#}
{#                          {%  endif %}#}
{##}
{#                      </div>#}
{##}
{#                      <div class="form-group row my-3 p-3">#}
{#                        <label for="id_group">#}
{#                          Группа#}
{#                        </label>#}
{#                              {% if is_edit %}#}
{#                                <select name="group" class="form-control" id="id_group">#}
{#                                  {{ form.group }}#}
{#                                </select>#}
{#                              {% else %}#}
{#                                {{ form.group }}#}
{#                              {% endif %}#}
{#                        <small id="id_group-help" class="form-text text-muted">#}
{#                          Группа, к которой будет относиться пост#}
{#                        </small>#}
{#                      </div>#}
{##}
{#                {% endfor %}#}
{##}
{#                  <div class="d-flex justify-content-end">#}
{#                    <button type="submit" class="btn btn-primary">#}
{#                      {% if is_edit %}#}
{#                        Сохранить#}
{#                      {% else %}#}
{#                        Добавить#}
{#                      {% endif %}#}
{#                    </button>#}
{#                  </div>#}
{##}
{#                {% if post.group %}#}
{#                    <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>#}
{#                {% endif %}#}
{##}
{##}
{#                </form>#}
{#            </div>#}
{#          </div>#}
{#        </div>#}
{#      </div>#}
{#    </main>#}
{#{% endblock %}#}

yatube/templates/posts/follow.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Избранные авторы{% endblock %}
{% block content %}

{% load cache %}
{% cache 20 sidebar %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
      <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      </p>
      <p>
      <p>{{ post.text }}</p>
          <a href="{% url 'posts:profile' post.author.username %}">подробнее</a>
      <p>
      {% if post.group %}
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %}

yatube/templates/posts/group_list.html
{% extends 'base.html' %}
{% load thumbnail %}
{% block title %}Страница группы: {{ group.title }}{% endblock %}
{% block content %}
<div class="container py-5">
<h1>{{ group.title }}</h1>
    <p>{{ group.description }}</p>

<body>
  <div class="container py-5">
    <h1>Последние обновления на сайте</h1>
    <article>
    {% for post in page_obj %}
      <ul>
        <li>
          Автор: {{ post.author.get_full_name }}
        </li>
        <li>
          Дата публикации: {{ post.pub_date|date:"d E Y" }}
        </li>
      </ul>
      <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      </p>
      <p>{{ post.text }}</p>
      <a href="{% url 'posts:index' %}">все записи группы</a>
      {% if not forloop.last %}<hr>{% endif %}
    {% endfor %}
    </article>
    <!-- под последним постом нет линии -->
  </div>
</body>
{% include 'posts/includes/paginator.html' %}
{% endblock %}

yatube/templates/posts/index.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Последние обновления на сайте{% endblock %}
{% block content %}

{% load cache %}
{% cache 20 sidebar %}
  {% include 'posts/includes/switcher.html' %}
  {% for post in page_obj %}
      <p>
        {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
            <img class="card-img my-2" src="{{ im.url }}">
        {% endthumbnail %}
      </p>
      <p>
      <p>{{ post.text }}</p>
          <a href="{% url 'posts:post_detail' post.id %}">подробнее</a>
      <p>
      {% if post.group %}
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
      {% endif %}
      {% if not forloop.last %}<hr>{% endif %}
  {% endfor %}
{% include 'posts/includes/paginator.html' %}
{% endcache %}
{% endblock %}

yatube/templates/posts/post_detail.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}{{ post_info.text|truncatechars:30 }}{% endblock %}
{% block content %}
    <main>
      <div class="row">
        <aside class="col-12 col-md-3">
          <ul class="list-group list-group-flush">
            <li class="list-group-item">
              Дата публикации: {{ post_info.pub_date|date:"d E Y" }}
            </li>

            {% if post_info.group %}
            <li class="list-group-item">
              Группа: {{post_info.group.title}}
            <p>
            <a href="{% url 'posts:group_posts' post_info.group.slug %}">
                все записи группы
              </a>
            </li>
            {% endif %}

            <li class="list-group-item">
              Автор: {{ post_info.author.get_full_name }}
            </li>
            <li class="list-group-item d-flex justify-content-between align-items-center">
              Всего постов автора:  <span >{{ post_info.author.posts.count }}</span>
            </li>
            <li class="list-group-item">
              <a href="{% url 'posts:profile' post_info.author.username %}">
                все посты пользователя
              </a>
            </li>
          </ul>
        </aside>
        <article class="col-12 col-md-9">
          <p>
          <p>
          {{ post_info.text }}
          </p>
          <p>
          <p>
            {% thumbnail post_info.image "960x339" crop="center" upscale=True as im %}
                <img class="card-img my-2" src="{{ im.url }}">
            {% endthumbnail %}
          </p>
              <a href="{% url 'posts:post_edit' post_id %}">
                редактировать
              </a>
        </article>
      </div>

    {% load user_filters %}

    {% if user.is_authenticated %}
      <div class="card my-4">
        <h5 class="card-header">Добавить комментарий:</h5>
        <div class="card-body">
          <form method="post" action="{% url 'posts:add_comment' post_id %}">
            {% csrf_token %}
            <div class="form-group mb-2">
              {{ form.text|addclass:"form-control" }}
            </div>
            <button type="submit" class="btn btn-primary">Отправить</button>
          </form>
        </div>
      </div>
    {% endif %}

    {% for comment in comments %}
      <div class="media mb-4">
        <div class="media-body">
          <h5 class="mt-0">
            <a href="{% url 'posts:profile' comment.author.username %}">
              {{ comment.author.username }}
            </a>
          </h5>
          <p>
            {{ comment.text }}
          </p>
        </div>
      </div>
    {% endfor %}

    </main>
{% endblock %}

yatube/templates/posts/profile.html
{% extends "base.html" %}
{% load thumbnail %}
{% block title %}Профайл пользователя: {{ author.get_full_name }}{% endblock %}
{% block content %}
    <main>
      <div class="container py-5">
      <div class="mb-5">
        <h1>Все посты пользователя: {{ author.get_full_name }}</h1>
        <h3>Всего постов: {{author.posts.count}} </h3>
            {% if author != user %}
            {% if following %}
                <a
                  class="btn btn-lg btn-light"
                  href="{% url 'posts:profile_unfollow' author.username %}" role="button"
                >
                  Отписаться
                </a>
              {% else %}
                  <a
                    class="btn btn-lg btn-primary"
                    href="{% url 'posts:profile_follow' author.username %}" role="button"
                  >
                    Подписаться
                  </a>
            {% endif %}
            {% endif %}
        {% for post in page_obj %}
        <article>
          <ul>
           <p>
            <li>
              Автор: {{ author.get_full_name }}
              <a href="{% url 'posts:profile' post.author.username %}">
                  все посты пользователя
              </a>
            </li>
            <li>
              Дата публикации: {{ post.pub_date|date:"d E Y" }}
            </li>
          </ul>
                <p>
                    {% thumbnail post.image "960x339" crop="center" upscale=True as im %}
                        <img class="card-img my-2" src="{{ im.url }}">
                    {% endthumbnail %}
                </p>
                <p>
                    {{ post.text }}
                </p>
            <div>
            <a href="{% url 'posts:post_detail' post.pk %}">подробная информация </a>
            </div>
            <div>
            {% if post.group %}
              <a href="{% url 'posts:group_posts' post.group.slug %}">все записи группы</a>
            {% endif %}
            </div>
            {% endfor %}
            {% include 'posts/includes/paginator.html' %}
        </article>
        <hr>
      </div>
    </main>
{% endblock %}

yatube/templates/posts/profile_follow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

yatube/templates/posts/profile_unfollow.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>